#!/bin/python

import os
import sys

#argument=int(sys.argv[1])
#i=1
#while i <= argument:
#	print "#",
#	while i <= argument:
#		print "#"
#		i+=1
#	print ''
#	i+=1
for argument in range(1,5):
	for i in range(1,5):
		print "#",
	print''
